// Generates packages/grammar/src/generated/property-map.ts from TTR.g4.
// Run via `pnpm --filter @modeler/grammar prebuild` (tsx). Paths are resolved
// from this script's own location so it works regardless of cwd.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const grammarPath = resolve(scriptDir, '../src/TTR.g4');
const outputPath = resolve(scriptDir, '../src/generated/property-map.ts');
const versionOutputPath = resolve(scriptDir, '../src/generated/version.ts');

const grammar = readFileSync(grammarPath, 'utf-8');

// Extract the canonical grammar version from the `@grammar-version:` marker
// in TTR.g4's header. This keeps the .g4 file as the single source of truth —
// the marker survives sync-to-ai-platform.sh so the Kotlin side sees the same
// version string when it regenerates from the vendored copy.
const versionMatch = grammar.match(/^\/\/\s*@grammar-version:\s*(\d+\.\d+)\s*$/m);
if (!versionMatch) {
  throw new Error(
    'TTR.g4 is missing the `// @grammar-version: X.Y` marker. ' +
      'Add it to the header comment before regenerating.',
  );
}
const grammarVersion = versionMatch[1];

// A `<x>Property` (or `<x>Property_`) sub-rule maps to a property name by
// stripping the suffixes, with two grammar-rule names that don't match their
// property name 1:1.
const RULE_NAME_OVERRIDES: Record<string, string> = {
  searchBlock: 'search',
  columnNamesList: 'columnNames',
};

function ruleToPropertyName(rule: string): string {
  const base = rule.replace(/_$/, '').replace(/Property$/, '');
  return RULE_NAME_OVERRIDES[base] ?? base;
}

// Ordered property names referenced by a `<ruleName> : aProperty | bProperty ;`
// rule. Anchored at line start so e.g. `entityProperty` does not match the tail
// of `er2dbEntityProperty`. Handles single- and multi-line rule bodies.
function extractProps(ruleName: string): string[] {
  const m = grammar.match(new RegExp(`^${ruleName}\\s*:\\s*([^;]+);`, 'm'));
  if (!m) return [];
  const subRules = m[1].match(/\w+Property_?/g) ?? [];
  return subRules.map(ruleToPropertyName);
}

const typeMap: Record<string, string> = {
  description: 'string',
  tags: 'list of strings',
  version: 'string',
  primaryKey: 'list of strings',
  columns: 'list of column definitions',
  indices: 'list of index definitions',
  constraints: 'list of constraint definitions',
  definitionSql: 'string',
  type: 'data type',
  optional: 'boolean',
  isKey: 'boolean',
  searchable: 'boolean',
  indexed: 'boolean',
  from: 'reference',
  to: 'reference',
  parameters: 'list of parameter definitions',
  resultColumns: 'list of column definitions',
  labelPlural: 'string',
  nameAttribute: 'reference',
  name: 'identifier',
  codeAttribute: 'reference',
  aliases: 'list of strings',
  attributes: 'list of attribute definitions',
  cardinality: 'object',
  join: 'list',
  entity: 'reference',
  attribute: 'reference',
  relation: 'reference',
  fk: 'reference',
  target: 'object',
  whereFilter: 'object',
  language: 'language',
  sourceText: 'string',
  length: 'number',
  precision: 'number',
  label: 'localized string',
  paramLabel: 'string',
  direction: 'identifier',
  displayLabel: 'localized string',
  roles: 'list of identifiers',
  valueLabels: 'value labels',
  role: 'reference',
  keywords: 'localized string list',
  patterns: 'list of strings',
  descriptions: 'localized string list',
  examples: 'list of strings',
  fuzzy: 'boolean',
  search: 'search block',
  mapping: 'mapping block or reference',
};

const allKinds = [
  'model',
  'table',
  'view',
  'column',
  'index',
  'constraint',
  'fk',
  'procedure',
  'entity',
  'attribute',
  'relation',
  'er2dbEntity',
  'er2dbAttribute',
  'er2dbRelation',
  'query',
  'role',
  'er2cncRole',
];

const searchSubProperties = extractProps('searchSubProperty');

let output = `// AUTO-GENERATED by packages/grammar/scripts/extract-property-map.ts
// Do not edit manually — regenerate with: pnpm --filter @modeler/grammar prebuild

export type DefinitionKind =
`;

for (let i = 0; i < allKinds.length; i++) {
  output += `  | '${allKinds[i]}'`;
}
output += ';\n\n';

output += 'export interface PropertyInfo {\n  name: string;\n  type: string;\n}\n\n';

output += 'export const PROPERTY_MAP: Record<DefinitionKind, PropertyInfo[]> = {\n';
for (const kind of allKinds) {
  const props = extractProps(`${kind}Property`);
  const infos = props.map((p) => `{ name: '${p}', type: '${typeMap[p] ?? 'unknown'}' }`);
  output += `  ${kind}: [${infos.join(', ')}],\n`;
}
output += '};\n\n';

output += `export const SEARCH_SUB_PROPERTIES: string[] = [${searchSubProperties.map((p) => `'${p}'`).join(', ')}];\n`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output);
console.log(`Generated property-map.ts with ${allKinds.length} kinds`);

const versionOutput = `// AUTO-GENERATED by packages/grammar/scripts/extract-property-map.ts
// Do not edit manually — bump the \`@grammar-version\` marker in TTR.g4 and
// regenerate with: pnpm --filter @modeler/grammar prebuild

export const TTR_GRAMMAR_VERSION = '${grammarVersion}' as const;
`;

writeFileSync(versionOutputPath, versionOutput);
console.log(`Generated version.ts (TTR grammar version ${grammarVersion})`);
