export enum DiagnosticCode {
  ParseError = 'ttr/parse-error',
  ParseRecoveryInfo = 'ttr/parse-recovery-info',
  UnknownProperty = 'ttr/unknown-property',
  UnresolvedReference = 'ttr/unresolved-reference',
  DuplicateDefinition = 'ttr/duplicate-definition',
  RequiredPropertyMissing = 'ttr/required-property-missing',
  InvalidType = 'ttr/invalid-type',
  EntityAttributeNotFound = 'ttr/entity-attribute-not-found',
  PrimaryKeyColumnNotFound = 'ttr/primary-key-column-not-found',
  WrongFileKind = 'ttr/wrong-file-kind',
  UnimportedReference = 'ttr/unimported-reference',
  UnusedImport = 'ttr/unused-import',
  WildcardWithNoMatches = 'ttr/wildcard-with-no-matches',
  DuplicateImport = 'ttr/duplicate-import',
  CircularPackageDependency = 'ttr/circular-package-dependency',
  PackageDeclarationMismatch = 'ttr/package-declaration-mismatch',
  PackagePrefixDivergence = 'ttr/package-prefix-divergence',
  InvalidPackageSegment = 'ttr/invalid-package-segment',
  MissingPackageDeclaration = 'ttr/missing-package-declaration',
  // Subject-area resolution (v3.0 `def area`; formerly `.ttrd` domain).
  AreaMemberNotFound = 'ttr/area-member-not-found',
  AreaEmpty = 'ttr/area-empty',
  DuplicateArea = 'ttr/duplicate-area',
  AreaRedundantMember = 'ttr/area-redundant-member',
  AmbiguousReference = 'ttr/ambiguous-reference',
  GraphObjectNotFound = 'ttr/graph-object-not-found',
  GraphLayoutStaleNode = 'ttr/graph-layout-stale-node',
  GraphObjectsEmpty = 'ttr/graph-objects-empty',
  GraphNameMismatch = 'ttr/graph-name-mismatch',
  FileOrdering = 'ttr/file-ordering',
  FuzzyWithoutSearchable = 'ttr/fuzzy-without-searchable',
  DuplicateSearchProperty = 'ttr/duplicate-search-property',
  // Grounding Phase 1 (grammar 4.2): a `semantics { … }` entry whose value is a
  // nested object/list rather than a scalar. Keeps ttr-semantics' input flat.
  SemanticsNonScalarValue = 'ttr/semantics-non-scalar',
  DuplicateBinding = 'ttr/duplicate-binding',
  // qname-redesign (contracts §5): manifest schema config + slot discipline.
  SchemaNameCollision = 'ttr/schema-name-collision',
  UnknownPackageSchema = 'ttr/unknown-package-schema',
  SchemaOnLogicalModel = 'ttr/schema-on-logical-model',
  RequireQualifiedRefs = 'ttr/require-qualified-refs',
  // embedded-sql (DESIGN §5/§6): tagged-block tag resolution.
  UnknownLanguageTag = 'ttr/unknown-language-tag',
  LanguageTagMismatch = 'ttr/language-tag-mismatch',
  DeprecatedLanguageProperty = 'ttr/deprecated-language-property',
  // v3.1 MD (multidimensional) model — contracts §7. Logical + binding codes.
  MdUnknownSchemaDef = 'md/unknown-schema-def',
  MdUnknownRef = 'md/unknown-ref',
  MdAttrNeedsDomain = 'md/attr-needs-domain',
  MdAttrTypeInMd = 'md/attr-type-in-md',
  ErAttrDomainInEr = 'er/attr-domain-in-er',
  MdDimKeyUnknown = 'md/dim-key-unknown',
  MdDimMultipleKeys = 'md/dim-multiple-keys',
  MdKindOnScalar = 'md/kind-on-scalar',
  MdBadRestrictValue = 'md/bad-restrict-value',
  MdUnknownRestrictClause = 'md/unknown-restrict-clause',
  MdBoundDomainNoSource = 'md/bound-domain-no-source',
  MdUnknownCalcMap = 'md/unknown-calc-map',
  MdBadCalcArgs = 'md/bad-calc-args',
  MdCalcTypeMismatch = 'md/calc-type-mismatch',
  MdCalcCardinalityConflict = 'md/calc-cardinality-conflict',
  MdTableMapNoBinding = 'md/table-map-no-binding',
  MdNoHierarchyStep = 'md/no-hierarchy-step',
  MdAmbiguousHierarchyStep = 'md/ambiguous-hierarchy-step',
  MdLevelNotInDim = 'md/level-not-in-dim',
  MdSemiadditiveNoValidby = 'md/semiadditive-no-validby',
  MdNonadditiveRecomputeUnsupported = 'md/nonadditive-recompute-unsupported',
  MdGrainRefUnknown = 'md/grain-ref-unknown',
  MdCubeletGrainUncovered = 'md/cubelet-grain-uncovered',
  MdGrainNotLeaf = 'md/grain-not-leaf',
  MdShapeMeasureMismatch = 'md/shape-measure-mismatch',
  MdMultisourceGrainMismatch = 'md/multisource-grain-mismatch',
  MdSourceOnUnboundDomain = 'md/source-on-unbound-domain',
  MdBindingOnCalcMap = 'md/binding-on-calc-map',
  MdMapColumnsIncomplete = 'md/map-columns-incomplete',
  MdMd2erPhysicalProp = 'md/md2er-physical-prop',
  MdIncompleteJournaling = 'md/incomplete-journaling',
  // embedded-sql (DESIGN §12.8 / contracts §5.1): SQL reference resolution
  // against the TTR `db` symbol table. Best-effort (warnings); see §3.4/§3.5.
  SqlUnknownTable = 'sql-unknown-table',
  SqlUnknownColumn = 'sql-unknown-column',
  SqlAmbiguousColumn = 'sql-ambiguous-column',
  SqlColumnNotOnAlias = 'sql-column-not-on-alias',
  SqlUndeclaredParam = 'sql-undeclared-param',
  SqlUnusedParam = 'sql-unused-param',
}

export enum DiagnosticSeverity {
  Error = 'error',
  Warning = 'warning',
  Information = 'information',
  Hint = 'hint',
}

export interface DiagnosticEntry {
  code: DiagnosticCode;
  message: string;
  severity: DiagnosticSeverity;
}