// SPDX-License-Identifier: Apache-2.0
package org.tatrman.ttrp.materialize

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldStartWith
import org.tatrman.ttr.parser.loader.TtrLoader
import org.tatrman.ttr.semantics.md.BindingShape
import org.tatrman.ttrp.resolve.MdRepo
import java.nio.file.Files

/**
 * S5C-B.2 (compile side, MDS7) — the generated `.ttrm` [MaterializeEmitter] writes for a fresh materialize.
 * Pins the properties the architecture demands of generated model text: a do-not-edit header, **deterministic**
 * content, **idempotent** re-emission (full-file replace with identical bytes), sensitivity to a changed
 * `with`, and a clean **round-trip** — the file parses and the next compile ([MdRepo]) sees the cubelet as a
 * regular one.
 */
class GeneratedTtrmSpec :
    StringSpec({

        val wide =
            MaterializeSpec(
                "fc",
                listOf("Customer.name", "Time.day"),
                "net",
                MatShape.WIDE,
                "db.dbo.md_fc",
                MatJournal.OVERWRITE,
            )
        val long =
            MaterializeSpec(
                "fc",
                listOf("Customer.name", "Time.day"),
                "net",
                MatShape.LONG,
                "db.dbo.md_fc",
                MatJournal.OVERWRITE,
            )

        "the generated content carries the do-not-edit header above the model directive" {
            val text = MaterializeEmitter.render(wide)
            text shouldStartWith "// Generated by TTR-P materialize"
            text shouldContain "DO NOT EDIT"
            text shouldContain "\nmodel md\n"
        }

        "rendering is deterministic — the same spec yields byte-identical content" {
            MaterializeEmitter.render(wide) shouldBe MaterializeEmitter.render(wide)
        }

        "a changed `with` (shape) changes the content" {
            MaterializeEmitter.render(wide) shouldNotBe MaterializeEmitter.render(long)
        }

        "the generated file parses" {
            TtrLoader.parseString(MaterializeEmitter.render(wide)).ok shouldBe true
        }

        "emission writes <modelsRoot>/generated/md/<name>.ttrm and is idempotent" {
            val root = Files.createTempDirectory("mat-gen")
            val path = MaterializeEmitter.emit(root, wide)
            path shouldBe root.resolve("generated").resolve("md").resolve("fc.ttrm")
            val first = Files.readString(path)
            // Re-materialising the same spec rewrites byte-identical content (full-file replace, no drift).
            MaterializeEmitter.emit(root, wide)
            Files.readString(path) shouldBe first
        }

        "re-materialising with a changed `with` updates the file" {
            val root = Files.createTempDirectory("mat-gen")
            MaterializeEmitter.emit(root, wide)
            val before = Files.readString(MaterializeEmitter.generatedPath(root, "fc"))
            MaterializeEmitter.emit(root, long)
            Files.readString(MaterializeEmitter.generatedPath(root, "fc")) shouldNotBe before
        }

        "the next compile (MdRepo) sees the materialized cubelet as a regular one" {
            val root = Files.createTempDirectory("mat-gen")
            MaterializeEmitter.emit(root, wide)
            val loaded = MdRepo.loadFrom(root)!!
            ("fc" in loaded.model.cubelets) shouldBe true
            loaded.model.cubelets
                .getValue("fc")
                .grain shouldBe listOf("Customer.name", "Time.day")
            val binding = loaded.bindings.cubelets.getValue("fc")
            binding.table shouldBe "db.dbo.md_fc"
            binding.shape shouldBe BindingShape.Wide
        }
    })
