// SPDX-License-Identifier: Apache-2.0
package org.tatrman.ttrp.emit.airflow3

/**
 * PL-P5.S4 — the **door-calling** (platform, E-3-α-1) Airflow 3 DAG: a single whole-program task that runs the
 * program through the platform program door (contracts §15), keeping the policy hall intact (a frontend, NOT a
 * native runtime). The task obtains a client-credentials token from the platform IdP token endpoint, `POST`s
 * `/v1/runs`, polls `GET /v1/runs/{id}` to a terminal state, and on kill `POST`s `/v1/runs/{id}/cancel`.
 *
 * The door base URL, IdP token URL and principal client-id all come from the **one** Airflow Connection named by
 * the world instance entry ([doorConnection]) — no URL and no secret is written into this file (B-4). Pure string
 * template with two substitutions (dag id + connection ref) ⇒ byte-deterministic.
 */
internal object DoorCallingDagRenderer {
    fun render(
        dagId: String,
        envelope: String,
        doorConnection: String,
    ): String {
        // Single-pass substitution: each placeholder is replaced exactly once, left to right, and the inserted
        // value is never re-scanned — so a value that itself contains a placeholder token (e.g. a program named
        // `p__CONN_ID__`) cannot be corrupted by a later pass, unlike a chain of `.replace(...)` calls.
        val subs = mapOf("__DAG_ID__" to dagId, "__ENVELOPE__" to envelope, "__CONN_ID__" to doorConnection)
        // The lambda form of Regex.replace inserts the returned string verbatim (no group-reference expansion),
        // so a value containing `$` or `\` is substituted literally.
        return Regex("__(?:DAG_ID|ENVELOPE|CONN_ID)__").replace(TEMPLATE) { m -> subs.getValue(m.value) }
    }

    private val TEMPLATE =
        """
        # Generated by ttrp — Airflow 3 door-calling DAG (E-3-α-1, a platform frontend). Do not edit.
        from __future__ import annotations

        import json
        import time
        import urllib.parse
        import urllib.request
        from datetime import datetime

        from airflow.sdk import DAG, BaseOperator, BaseHook


        class TtrDoorRunOperator(BaseOperator):
            "Run the whole program through the platform program door (POST /v1/runs, poll, cancel)."

            # Bound the poll so a door run that never reaches a terminal state fails the task (and cancels the
            # run) instead of hanging the worker forever.
            poll_interval = 5
            poll_timeout = 21600

            def __init__(self, conn_id: str, envelope: str, params=None, **kwargs) -> None:
                super().__init__(**kwargs)
                self.conn_id = conn_id
                self.envelope = envelope
                self.params = params or {}
                self._run_id = None

            def _token(self, conn):
                extra = conn.extra_dejson
                data = urllib.parse.urlencode(
                    {
                        "grant_type": "client_credentials",
                        "client_id": conn.login,
                        "client_secret": conn.password,
                    }
                ).encode()
                req = urllib.request.Request(extra["token_url"], data=data)
                with urllib.request.urlopen(req) as resp:
                    return json.load(resp)["access_token"]

            def _door(self, conn):
                return conn.host.rstrip("/")

            def execute(self, context):
                conn = BaseHook.get_connection(self.conn_id)
                token = self._token(conn)
                body = json.dumps(
                    {"envelope": self.envelope, "params": self.params, "trigger": "airflow"}
                ).encode()
                req = urllib.request.Request(
                    self._door(conn) + "/v1/runs",
                    data=body,
                    headers={"Authorization": "Bearer " + token, "Content-Type": "application/json"},
                )
                with urllib.request.urlopen(req) as resp:
                    self._run_id = json.load(resp)["runId"]
                self._poll(conn, token)
                return self._run_id

            def _poll(self, conn, token):
                deadline = time.monotonic() + self.poll_timeout
                while True:
                    req = urllib.request.Request(
                        self._door(conn) + "/v1/runs/" + self._run_id,
                        headers={"Authorization": "Bearer " + token},
                    )
                    with urllib.request.urlopen(req) as resp:
                        state = json.load(resp)["state"]
                    if state in ("succeeded", "failed", "cancelled"):
                        if state != "succeeded":
                            raise RuntimeError("door run " + self._run_id + " ended: " + state)
                        return
                    if time.monotonic() >= deadline:
                        self.on_kill()
                        raise TimeoutError(
                            "door run " + self._run_id + " did not reach a terminal state within "
                            + str(self.poll_timeout) + "s"
                        )
                    time.sleep(self.poll_interval)

            def on_kill(self):
                if not self._run_id:
                    return
                conn = BaseHook.get_connection(self.conn_id)
                token = self._token(conn)
                req = urllib.request.Request(
                    self._door(conn) + "/v1/runs/" + self._run_id + "/cancel",
                    data=b"",
                    headers={"Authorization": "Bearer " + token},
                )
                urllib.request.urlopen(req)


        with DAG(
            dag_id="__DAG_ID__",
            schedule=None,
            start_date=datetime(2024, 1, 1),
            catchup=False,
            tags=["ttrp", "door-calling"],
        ) as dag:
            run = TtrDoorRunOperator(
                task_id="run___DAG_ID__",
                conn_id="__CONN_ID__",
                envelope="__ENVELOPE__",
            )
        """.trimIndent() + "\n"
}
