// SPDX-License-Identifier: Apache-2.0
package org.tatrman.ttrp.emit.airflow3

import org.tatrman.ttrp.emit.spi.EmitIsland
import org.tatrman.ttrp.emit.spi.OrchestrationGraph

/**
 * PL-P5.S4 — the **native** (standalone, E-3-β) Airflow 3 DAG: one operator per island, wave order as task
 * dependencies, islands invoked per the F-lite bindings (psql → `BashOperator`, python3 → `PythonOperator`
 * running the island script). Connections are sourced from the user's own Airflow Connections
 * (`{{ conn.<id>.get_uri() }}`) — **no platform reference anywhere** (H-8: credential-bounded, not door-bounded).
 * Pure string codegen from a fixed template (no timestamps; a constant `start_date`) ⇒ byte-deterministic.
 */
internal object NativeDagRenderer {
    fun render(
        dagId: String,
        graph: OrchestrationGraph,
    ): String {
        val islandsByName = graph.islands.associateBy { it.name }
        val transfersByToken = graph.transfers.associateBy { tokenOf(it.file) }
        val sb = StringBuilder()

        sb.append("# Generated by ttrp — Airflow 3 native DAG (E-3-β). Do not edit.\n")
        sb.append("from __future__ import annotations\n\n")
        sb.append("import subprocess\n")
        sb.append("import sys\n")
        sb.append("from datetime import datetime\n\n")
        sb.append("from airflow.sdk import DAG\n")
        sb.append("from airflow.providers.standard.operators.bash import BashOperator\n")
        sb.append("from airflow.providers.standard.operators.python import PythonOperator\n\n\n")
        sb.append("def _run_script(path: str) -> None:\n")
        sb.append("    subprocess.run([sys.executable, path], check=True)\n\n\n")
        sb.append("with DAG(\n")
        sb.append("    dag_id=\"").append(dagId).append("\",\n")
        sb.append("    schedule=None,\n")
        sb.append("    start_date=datetime(2024, 1, 1),\n")
        sb.append("    catchup=False,\n")
        sb.append("    tags=[\"ttrp\", \"native\"],\n")
        sb.append(") as dag:\n")

        // One Airflow-legal, collision-free id per wave token — used for BOTH the operator variable and the
        // `task_id`, so the `>>` edges bind to the right operator. Island/transfer names are SSA labels
        // ([A-Za-z0-9_~#]): `~`/`#` are illegal in an Airflow task_id and non-injective under sanitization, so
        // they fold to `_` and any collision is broken deterministically. Without this, an anonymous `~n` or an
        // SSA-versioned `name#k` island emits a task_id Airflow rejects at DAG parse (the whole DAG never loads).
        val taskIds = taskIdsFor(graph.waves.flatten())

        // One operator per wave token, in wave then token order (deterministic).
        graph.waves.flatten().forEach { token ->
            val id = taskIds.getValue(token)
            val island = islandsByName[token]
            if (island != null) {
                sb.append(operatorFor(id, island, graph.connectionByIsland))
            } else {
                val transfer = transfersByToken[token] ?: error("wave token '$token' matches no island or transfer")
                sb.append(pythonOperator(id, id, transfer.file, transfer.connections))
            }
        }

        // Wave dependencies: every task in wave i is upstream of every task in wave i+1 (explicit pairwise edges).
        val edges =
            graph.waves.zipWithNext().flatMap { (up, down) ->
                up.flatMap { u -> down.map { d -> taskIds.getValue(u) to taskIds.getValue(d) } }
            }
        if (edges.isNotEmpty()) {
            sb.append("\n    # wave dependencies\n")
            edges.forEach { (u, d) ->
                sb
                    .append("    ")
                    .append(u)
                    .append(" >> ")
                    .append(d)
                    .append('\n')
            }
        }
        return sb.toString()
    }

    private fun operatorFor(
        id: String,
        island: EmitIsland,
        connectionByIsland: Map<String, String>,
    ): String =
        when (island.invocation) {
            "psql" -> {
                val conn =
                    connectionByIsland[island.name] ?: error("no connection bound for psql island '${island.name}'")
                bashOperator(id, id, island.file, conn)
            }
            "python3" -> pythonOperator(id, id, island.file, island.connections)
            else -> error("unknown invocation '${island.invocation}' for island '${island.name}'")
        }

    /**
     * A psql island as a `BashOperator` with the verbatim F-lite invocation; the connection is an Airflow
     * Connection URI. [file] is the on-disk island path (`islands/<ssa-name>.sql`) and is emitted verbatim so it
     * resolves to the real file — safe unquoted because SSA names are `[A-Za-z0-9_~#]` (no space/shell metachar,
     * and the `~` is never word-initial in `islands/…`), so no word-splitting or tilde-expansion can occur.
     */
    private fun bashOperator(
        varName: String,
        taskId: String,
        file: String,
        conn: String,
    ): String =
        buildString {
            append("    ").append(varName).append(" = BashOperator(\n")
            append("        task_id=\"").append(taskId).append("\",\n")
            append("        bash_command='psql \"\$").append(conn)
            append("\" -v ON_ERROR_STOP=1 --no-psqlrc -f ").append(file).append("',\n")
            append("        env={\"").append(conn).append("\": \"{{ conn.").append(conn.lowercase())
            append(".get_uri() }}\"},\n")
            append("        append_env=True,\n")
            append("    )\n")
        }

    /** A python3 island/transfer as a `PythonOperator` running the island script file via the shared `_run_script`. */
    private fun pythonOperator(
        varName: String,
        taskId: String,
        file: String,
        connections: List<String>,
    ): String =
        buildString {
            append("    ").append(varName).append(" = PythonOperator(\n")
            append("        task_id=\"").append(taskId).append("\",\n")
            append("        python_callable=_run_script,\n")
            append("        op_args=[\"").append(file).append("\"],\n")
            if (connections.isNotEmpty()) {
                // Connections a python island reads (rare) are named in the DAG so an operator env/secret can bind
                // them user-side; the value stays a Connection URI reference, never material.
                val env =
                    connections.toSortedSet().joinToString(
                        ", ",
                    ) { "\"$it\": \"{{ conn.${it.lowercase()}.get_uri() }}\"" }
                append("        op_kwargs={\"env\": {").append(env).append("}},\n")
            }
            append("    )\n")
        }

    private fun tokenOf(file: String): String = file.substringAfterLast('/').substringBeforeLast('.')

    /**
     * A deterministic, collision-free map from each wave token to an Airflow-legal id that is ALSO a valid Python
     * identifier — so `task_id` == operator variable and the `>>` edges bind to the right operator. Two labels
     * that fold to the same identifier (e.g. `a#2` and `a_2`) are de-collided by a `_2`, `_3`, … suffix in wave
     * order (every emitted id is registered, so no two tokens ever share one).
     */
    private fun taskIdsFor(tokens: List<String>): Map<String, String> {
        val used = HashSet<String>()
        val out = LinkedHashMap<String, String>()
        tokens.forEach { token ->
            val base = idOf(token)
            var name = base
            var n = 2
            while (!used.add(name)) {
                name = "${base}_$n"
                n++
            }
            out[token] = name
        }
        return out
    }

    /** One wave token → a valid Python identifier (letters/digits/`_`, never leading-digit). */
    private fun idOf(name: String): String {
        val cleaned = name.map { if (it.isLetterOrDigit() || it == '_') it else '_' }.joinToString("")
        return if (cleaned.isEmpty() || cleaned.first().isDigit()) "t_$cleaned" else cleaned
    }
}
