// SPDX-License-Identifier: Apache-2.0
package org.tatrman.ttrp.materialize

import org.tatrman.ttr.writer.TtrRenderer
import java.nio.file.Files
import java.nio.file.Path

/**
 * MD dot-path S5C-B.2 — the **compile-side** effect of materialize (`C := e`, R27 · MDS7): "materialization
 * writes model text, not model state." A fresh materialized cubelet's inferred definition ([MaterializeSpec])
 * is rendered to a generated `.ttrm` under `<modelsRoot>/generated/md/<name>.ttrm` through [TtrRenderer]
 * (B.1), so the model repo stays the single canonical truth and the next compile picks the cubelet up as a
 * regular one ([org.tatrman.ttrp.resolve.MdRepo] walks the whole models tree).
 *
 * The output is **deterministic** (constant header + [TtrRenderer]'s sorted, key-ordered rendering) and
 * **idempotent** (re-materializing the same spec rewrites byte-identical content; a changed `with` produces
 * changed content). Regeneration is a full-file replace — the do-not-edit header + deterministic body make
 * hand-edit drift a validation concern, not a merge (architecture §7). The header is prepended here rather
 * than via [TtrRenderer] because comments are not part of the rendered AST.
 *
 * The run-side effect (create-table + full-replace Store on the backing table) is S5C-B.2's run slice; this
 * writer only produces model text.
 */
object MaterializeEmitter {
    /** The do-not-edit banner every generated `.ttrm` carries (architecture §7 · MDS7). */
    val HEADER =
        listOf(
            "// Generated by TTR-P materialize (`:=`) — DO NOT EDIT.",
            "// This file is regenerated in full on every materialize; hand edits are overwritten.",
        ).joinToString("\n")

    /** The generated-model directory under a models root: `<modelsRoot>/generated/md`. */
    fun generatedDir(modelsRoot: Path): Path = modelsRoot.resolve("generated").resolve("md")

    /** The generated file for a materialized cubelet: `<modelsRoot>/generated/md/<name>.ttrm`. */
    fun generatedPath(
        modelsRoot: Path,
        name: String,
    ): Path = generatedDir(modelsRoot).resolve("$name.ttrm")

    /**
     * The full generated `.ttrm` text for [spec]: the do-not-edit header, then the `model <schemaCode>`
     * directive and the rendered cubelet + binding. Deterministic — the same spec always yields the same
     * bytes.
     */
    fun render(
        spec: MaterializeSpec,
        schemaCode: String = MaterializeSpec.DEFAULT_SCHEMA,
    ): String {
        val body = TtrRenderer.renderFile(schemaCode, namespace = null, definitions = spec.toDefinitions(schemaCode))
        return "$HEADER\n\n$body"
    }

    /**
     * Emit [spec] to `<modelsRoot>/generated/md/<name>.ttrm` (creating the directory), returning the path.
     * Full-file replace on every call — idempotent for an unchanged spec (identical bytes rewritten).
     */
    fun emit(
        modelsRoot: Path,
        spec: MaterializeSpec,
        schemaCode: String = MaterializeSpec.DEFAULT_SCHEMA,
    ): Path {
        val path = generatedPath(modelsRoot, spec.name)
        Files.createDirectories(path.parent)
        Files.writeString(path, render(spec, schemaCode))
        return path
    }
}
