// SPDX-License-Identifier: Apache-2.0
package org.tatrman.ttrp.bundle

/**
 * Generates `run.sh` — the F-lite executor (contracts §5): `set -euo pipefail`, a bash-version +
 * `TTR_CONN_*` pre-flight (exit 2), wipe-on-restart of `logs/ staging/ out/` (F-e α), wave
 * parallelism (`&` + pid array) with a `wait -n` early-abort loop that kills siblings and exits 1,
 * per-F-c invocations (`psql` / `python3`), display notices, final `exit 0`. Pure function of the
 * manifest + the per-island connection binding; deterministic.
 *
 * `connectionByIsland` supplies the `TTR_CONN_*` env var name each psql island reads (the manifest
 * island entry is connection-agnostic by contract §5); python3 islands/transfers read their own
 * creds from env inside the script (F-c-ii α).
 */
object RunShGenerator {
    fun generate(
        manifest: RunManifest,
        connectionByIsland: Map<String, String>,
    ): String {
        val islandsByName = manifest.islands.associateBy { it.name }
        val transfersByToken = manifest.transfers.associateBy { tokenOf(it.file) }
        val sb = StringBuilder()

        sb.appendLine("#!/usr/bin/env bash")
        sb.appendLine("# Generated by ttrp — do not edit. Wave-parallel executor (contracts §5).")
        sb.appendLine("set -euo pipefail")
        sb.appendLine()
        sb.appendLine("# --- pre-flight (exit 2 on failure) ---")
        sb.appendLine("if (( BASH_VERSINFO[0] < 4 )) || (( BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 3 )); then")
        sb.appendLine("  echo \"ttrp: bash >= 4.3 required (found \$BASH_VERSION)\" >&2; exit 2")
        sb.appendLine("fi")
        manifest.connections.forEach { conn ->
            sb.appendLine("[[ -z \"\${$conn:-}\" ]] && { echo \"missing $conn\" >&2; exit 2; }")
        }
        sb.appendLine()
        sb.appendLine("# --- wipe-on-restart (F-e) ---")
        sb.appendLine("rm -rf logs staging out && mkdir -p logs staging out")
        sb.appendLine()

        manifest.waves.forEachIndexed { i, wave ->
            sb.appendLine("# --- wave $i ---")
            sb.appendLine("pids=()")
            sb.appendLine("names=()")
            wave.forEach { token ->
                val cmd = commandFor(token, islandsByName, transfersByToken, connectionByIsland)
                sb.appendLine("$cmd > \"logs/$token.log\" 2>&1 &")
                sb.appendLine("pids+=(\$!); names+=(\"$token\")")
            }
            // wait -n early-abort loop: first nonzero kills siblings and exits 1.
            sb.appendLine("remaining=\${#pids[@]}")
            sb.appendLine("while (( remaining > 0 )); do")
            sb.appendLine("  if wait -n; then")
            sb.appendLine("    remaining=\$(( remaining - 1 ))")
            sb.appendLine("  else")
            sb.appendLine("    code=\$?")
            sb.appendLine("    for idx in \"\${!pids[@]}\"; do")
            sb.appendLine(
                "      if kill -0 \"\${pids[idx]}\" 2>/dev/null; then kill \"\${pids[idx]}\" 2>/dev/null || true; fi",
            )
            sb.appendLine("    done")
            sb.appendLine("    wait 2>/dev/null || true")
            sb.appendLine("    for idx in \"\${!names[@]}\"; do")
            sb.appendLine("      echo \"FAILED island=\${names[idx]} exit=\$code log=logs/\${names[idx]}.log\" >&2")
            sb.appendLine("    done")
            sb.appendLine("    exit 1")
            sb.appendLine("  fi")
            sb.appendLine("done")
            sb.appendLine()
        }

        if (manifest.displays.isNotEmpty()) {
            sb.appendLine("# --- displays ---")
            manifest.displays.forEach { sb.appendLine("echo \"display ${it.name}: ${it.file}\"") }
            sb.appendLine()
        }
        sb.appendLine("exit 0")
        return sb.toString()
    }

    private fun commandFor(
        token: String,
        islands: Map<String, IslandEntry>,
        transfers: Map<String, TransferEntry>,
        connectionByIsland: Map<String, String>,
    ): String {
        islands[token]?.let { island ->
            return when (island.invocation) {
                "psql" -> {
                    val conn = connectionByIsland[island.name] ?: error("no connection bound for psql island '$token'")
                    "psql \"\$$conn\" -v ON_ERROR_STOP=1 --no-psqlrc -f ${island.file}"
                }
                "python3" -> "python3 ${island.file}"
                else -> error("unknown invocation '${island.invocation}' for island '$token'")
            }
        }
        transfers[token]?.let { return "python3 ${it.file}" }
        error("wave token '$token' matches no island or transfer")
    }

    private fun tokenOf(file: String): String = file.substringAfterLast('/').substringBeforeLast('.')
}
