// SPDX-License-Identifier: Apache-2.0
package org.tatrman.ttr.importschema.checklist

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.tatrman.ttr.importschema.dbmodel.IdentifierRename
import org.tatrman.ttr.importschema.er.ChecklistNote
import org.tatrman.ttr.importschema.er.ErDerivationResult
import org.tatrman.ttr.importschema.probe.Provenance

/**
 * The F5-β review checklist (S4·T4) — the confidence carrier that rides the same PR as the model.
 * Two artifacts beside the model files: `import-review.md` (human walkthrough) and
 * `import-review.json` (its machine twin, one documented schema). Q-3: the model text stays clean
 * canonical form; every judgement (collapses, proposed folds, evidence grades + probe numbers,
 * contradictions, unmatched columns, renames, the Q-5 coverage report) lives here.
 *
 * Deterministic (GI-2): sections sorted; no timestamps.
 */
object ReviewChecklist {
    private val json =
        Json {
            prettyPrint = true
            encodeDefaults = true
        }

    /** Q-5 coverage inputs the runner supplies (from the cascade + probe plan). */
    data class Coverage(
        val tablesInScope: Int,
        val tablesIntrospected: Int,
        val candidatesTotal: Int,
        val candidatesProbed: Int,
        /** Exact leftover list — candidates left unprobed because the budget ran out. */
        val unprobedForBudget: List<String>,
    )

    fun toJson(
        result: ErDerivationResult,
        renames: List<IdentifierRename>,
        coverage: Coverage,
    ): String = json.encodeToString(ReviewJson.serializer(), model(result, renames, coverage))

    fun toMarkdown(
        result: ErDerivationResult,
        renames: List<IdentifierRename>,
        coverage: Coverage,
    ): String {
        val m = model(result, renames, coverage)
        return buildString {
            appendLine("# Import review — ${m.pkg}")
            appendLine()
            appendLine("> Generated by `ttr import-schema`. This checklist is the confidence carrier;")
            appendLine("> the model text is clean canonical form. Walk each section and accept/correct in review.")
            appendLine()

            section(
                "Relations (evidence grades)",
                m.relations.map {
                    val prov =
                        it.provenance?.let { p ->
                            " · $p${if (it.orphanEstimate) " (orphan count is an estimate)" else ""}"
                        }
                            ?: ""
                    val orphans = it.orphanCount?.let { o -> " · orphans=$o" } ?: ""
                    "`${it.name}` ${it.from} → ${it.to} — **${it.grade}** (${it.rule})$prov$orphans"
                },
            )
            section("Junctions collapsed (silent M:N)", m.junctionsCollapsed)
            section("Folds PROPOSED (not applied — accept in review)", m.foldsProposed)
            section("Codebooks proposed (enum-like)", m.codebooksProposed)
            section("Contradictions (name says yes, data says no — kept OUT of the model)", m.contradictions)
            section("Unmatched columns (look like FKs, resolve to no table)", m.unmatchedColumns)
            section(
                "Renamed identifiers (original ← TTR name)",
                m.renamedIdentifiers.map {
                    "`${it.to}` ← `${it.from}` (${it.scope})"
                },
            )
            section("Unprobed — budget exhausted (Q-5)", m.unprobedForBudget)

            appendLine("## Coverage (Q-5)")
            appendLine()
            appendLine(
                "- Tables introspected: ${m.coverage.tablesIntrospected} of ${m.coverage.tablesInScope} in scope",
            )
            appendLine("- Candidates probed: ${m.coverage.candidatesProbed} of ${m.coverage.candidatesTotal}")
            if (m.coverage.unprobedCandidates.isNotEmpty()) {
                appendLine("- Unprobed (budget): ${m.coverage.unprobedCandidates.joinToString(", ")}")
            }
        }
    }

    private fun StringBuilder.section(
        title: String,
        items: List<String>,
    ) {
        appendLine("## $title")
        appendLine()
        if (items.isEmpty()) {
            appendLine("_none_")
        } else {
            items.sorted().forEach { appendLine("- $it") }
        }
        appendLine()
    }

    private fun model(
        result: ErDerivationResult,
        renames: List<IdentifierRename>,
        coverage: Coverage,
    ): ReviewJson {
        fun notesOf(kind: ChecklistNote.Kind) =
            result.notes
                .filter { it.kind == kind }
                .map { "${it.subject} — ${it.detail}" }
                .sorted()
        return ReviewJson(
            pkg = result.packageName,
            relations =
                result.relations
                    .map {
                        ReviewRelation(
                            name = it.name,
                            from = it.fromEntity,
                            to = it.toEntity,
                            grade = it.evidence.grade.name,
                            rule = it.evidence.rule,
                            provenance = it.evidence.provenance?.name,
                            orphanCount = it.evidence.orphanCount,
                            orphanEstimate = it.evidence.provenance == Provenance.SAMPLED,
                        )
                    }.sortedBy { it.name },
            junctionsCollapsed = notesOf(ChecklistNote.Kind.JUNCTION_COLLAPSED),
            foldsProposed = notesOf(ChecklistNote.Kind.HEADER_DETAIL_PROPOSED),
            codebooksProposed = notesOf(ChecklistNote.Kind.CODEBOOK_PROPOSED),
            contradictions = notesOf(ChecklistNote.Kind.CONTRADICTED),
            unmatchedColumns = notesOf(ChecklistNote.Kind.UNMATCHED_COLUMN),
            renamedIdentifiers =
                renames
                    .map { ReviewRename(it.sourceName, it.ttrName, "${it.kind} ${it.qualifier}") }
                    .sortedBy { it.to },
            unprobedForBudget = notesOf(ChecklistNote.Kind.UNPROBED_BUDGET),
            coverage =
                ReviewCoverage(
                    tablesInScope = coverage.tablesInScope,
                    tablesIntrospected = coverage.tablesIntrospected,
                    candidatesTotal = coverage.candidatesTotal,
                    candidatesProbed = coverage.candidatesProbed,
                    unprobedCandidates = coverage.unprobedForBudget.sorted(),
                ),
        )
    }
}

@Serializable
data class ReviewJson(
    val schemaVersion: Int = 1,
    @SerialName("package") val pkg: String,
    val relations: List<ReviewRelation>,
    val junctionsCollapsed: List<String>,
    val foldsProposed: List<String>,
    val codebooksProposed: List<String>,
    val contradictions: List<String>,
    val unmatchedColumns: List<String>,
    val renamedIdentifiers: List<ReviewRename>,
    val unprobedForBudget: List<String>,
    val coverage: ReviewCoverage,
)

@Serializable
data class ReviewRelation(
    val name: String,
    val from: String,
    val to: String,
    val grade: String,
    val rule: String,
    val provenance: String? = null,
    val orphanCount: Long? = null,
    val orphanEstimate: Boolean = false,
)

@Serializable
data class ReviewRename(
    val from: String,
    val to: String,
    val scope: String,
)

@Serializable
data class ReviewCoverage(
    val tablesInScope: Int,
    val tablesIntrospected: Int,
    val candidatesTotal: Int,
    val candidatesProbed: Int,
    val unprobedCandidates: List<String>,
)
