// SPDX-License-Identifier: Apache-2.0
package org.tatrman.ttrp.emit.kestra

import org.snakeyaml.engine.v2.api.Dump
import org.snakeyaml.engine.v2.api.DumpSettings
import org.snakeyaml.engine.v2.common.FlowStyle
import org.tatrman.ttrp.emit.spi.EmitIsland
import org.tatrman.ttrp.emit.spi.EmitRequest
import org.tatrman.ttrp.emit.spi.EmitResult
import org.tatrman.ttrp.emit.spi.EmitTransfer
import org.tatrman.ttrp.emit.spi.OrchestrationGraph
import org.tatrman.ttrp.emit.spi.TtrEmitPlugin
import java.util.SortedMap
import java.util.TreeMap

/**
 * PL-P5.S3 — the Kestra emit plugin (`targetId = "kestra"`, contracts §8, EQ-3). Renders a **declarative Kestra
 * flow** (`flow.yaml`) from the projected [OrchestrationGraph]: one `io.kestra.plugin.core.flow.Parallel` per
 * wave (sequential wave order), one task per island (`psql` → `io.kestra.plugin.scripts.shell.Script`, `python3`
 * → `io.kestra.plugin.scripts.python.Commands`), transfer edges as tasks in their wave, and each connection
 * surfaced as a `TTR_CONN_*` env placeholder wired to a Kestra secret — **never material** (contract §5/B-4).
 *
 * **Native / standalone (E-3-β).** The flow runs islands directly against the engines; the platform is NOWHERE
 * in it — no program-door URL appears in the output (H-8: credential-bounded, not door-bounded).
 *
 * **Pure data generation (the EQ-3 point).** A declarative YAML flow is reviewable data in the bundle, not
 * codegen — so `emit` is a PURE function of [OrchestrationGraph] rendered through a fixed-`DumpSettings`
 * snakeyaml-engine dumper (block style, fixed indent/width, `\n` breaks): same request ⇒ byte-identical
 * `flow.yaml` (the H-6 determinism obligation). Map insertion order is preserved (structural order is semantic);
 * connection sets are sorted (order is NOT semantic there).
 */
class KestraEmitPlugin : TtrEmitPlugin {
    override val targetId: String = "kestra"

    override val spiVersion: Int = TtrEmitPlugin.SPI_VERSION

    override fun executorTypeManifest(): String = EXECUTOR_MANIFEST

    override fun emit(request: EmitRequest): EmitResult {
        val flowYaml = renderFlow(request)
        val files: SortedMap<String, ByteArray> = TreeMap()
        files["flow.yaml"] = flowYaml.toByteArray()
        return EmitResult(files)
    }

    private fun renderFlow(request: EmitRequest): String {
        val graph = request.graph
        val islandsByName = graph.islands.associateBy { it.name }
        val transfersByToken = graph.transfers.associateBy { tokenOf(it.file) }

        val waveTasks =
            graph.waves.mapIndexed { i, wave ->
                linkedMapOf<String, Any>(
                    "id" to "wave_$i",
                    "type" to "io.kestra.plugin.core.flow.Parallel",
                    "tasks" to
                        wave.map { token -> taskFor(token, islandsByName, transfersByToken, graph.connectionByIsland) },
                )
            }

        val flow =
            linkedMapOf<String, Any>(
                "id" to sanitizeId(request.program.name.removeSuffix(".ttrp")),
                "namespace" to request.program.qname.ifBlank { DEFAULT_NAMESPACE },
                "description" to "Generated by ttrp — Kestra flow (contracts §8, EQ-3). Do not edit.",
                "tasks" to waveTasks,
            )
        return DUMP.dumpToString(flow)
    }

    /** One Kestra task for a wave [token]: an island (by name) or a transfer (by `tokenOf(file)`) — mirrors the bash resolution. */
    private fun taskFor(
        token: String,
        islands: Map<String, EmitIsland>,
        transfers: Map<String, EmitTransfer>,
        connectionByIsland: Map<String, String>,
    ): Map<String, Any> {
        islands[token]?.let { island ->
            return when (island.invocation) {
                "psql" -> {
                    val conn =
                        connectionByIsland[island.name]
                            ?: error("no connection bound for psql island '$token'")
                    linkedMapOf(
                        "id" to sanitizeId(island.name),
                        "type" to "io.kestra.plugin.scripts.shell.Script",
                        // The F-lite psql invocation binding, verbatim (contracts §5): fail hard on the first error.
                        "script" to "psql \"\$$conn\" -v ON_ERROR_STOP=1 --no-psqlrc -f ${island.file}",
                        "env" to envFor(listOf(conn)),
                    )
                }
                "python3" -> pythonTask(sanitizeId(island.name), island.file, island.connections)
                else -> error("unknown invocation '${island.invocation}' for island '$token'")
            }
        }
        transfers[token]?.let { transfer ->
            return pythonTask(sanitizeId(token), transfer.file, transfer.connections)
        }
        error("wave token '$token' matches no island or transfer")
    }

    /** A `python3 <file>` task (`python.Commands`); connections (if any) surface as sorted `TTR_CONN_*` env secrets. */
    private fun pythonTask(
        id: String,
        file: String,
        connections: List<String>,
    ): Map<String, Any> =
        buildMap {
            put("id", id)
            put("type", "io.kestra.plugin.scripts.python.Commands")
            put("commands", listOf("python3 $file"))
            if (connections.isNotEmpty()) put("env", envFor(connections))
        }

    /**
     * A Kestra `env` map: each connection var → a secret placeholder (`{{ secret("NAME") }}`) — the credential is
     * NEVER materialised in the flow (B-4). Keys are sorted (connection-set order is not semantic; sorting keeps
     * the dump deterministic).
     */
    private fun envFor(connections: List<String>): Map<String, String> {
        val env = linkedMapOf<String, String>()
        connections.toSortedSet().forEach { conn -> env[conn] = "{{ secret(\"$conn\") }}" }
        return env
    }

    private fun tokenOf(file: String): String = file.substringAfterLast('/').substringBeforeLast('.')

    /** Kestra ids are `[A-Za-z0-9._-]+`; TTR identifiers already fit, but sanitize defensively. */
    private fun sanitizeId(raw: String): String {
        val cleaned =
            raw
                .map {
                    if (it.isLetterOrDigit() ||
                        it == '.' ||
                        it == '_' ||
                        it == '-'
                    ) {
                        it
                    } else {
                        '_'
                    }
                }.joinToString("")
        return cleaned.ifBlank { "flow" }
    }

    companion object {
        private const val DEFAULT_NAMESPACE = "tatrman"

        /**
         * Fixed dump settings = a deterministic dumper. Block style everywhere, 2-space indent, a wide fixed line
         * width so commands never wrap on width, `\n` breaks, no `---`/`...` markers.
         */
        private val DUMP: Dump =
            Dump(
                DumpSettings
                    .builder()
                    .setDefaultFlowStyle(FlowStyle.BLOCK)
                    .setIndent(2)
                    .setWidth(1_000)
                    .setBestLineBreak("\n")
                    .setExplicitStart(false)
                    .setExplicitEnd(false)
                    .build(),
            )

        private val EXECUTOR_MANIFEST: String =
            KestraEmitPlugin::class.java
                .getResourceAsStream("/org/tatrman/ttrp/emit/kestra/kestra-executor.ttrm")
                ?.use { it.readBytes().decodeToString() }
                ?: error("ttr-emit-kestra: bundled kestra-executor.ttrm resource is missing")
    }
}
