// SPDX-License-Identifier: Apache-2.0
package org.tatrman.ttrp.project

import org.tatrman.ttrp.ast.SourceLocation
import org.tatrman.ttrp.diagnostics.Severity
import org.tatrman.ttrp.diagnostics.TtrpDiagnostic
import org.tatrman.ttrp.diagnostics.TtrpDiagnosticId
import org.tomlj.Toml

/**
 * `ttr.lock` (contracts §3) — committed at the project root, generated by `ttr fetch`, pins **canon
 * only** (stats never appear). Server URL + auth live in project config, NEVER here.
 *
 * The lock's **bytes are content-relevant** (a fetch is a reviewable lock diff), so writing is a
 * hand-rolled deterministic serializer (sorted sections/keys, fixed formatting) — `tomlj` parses but
 * does not round-trip formatting (tracker Library card).
 */
data class TtrLock(
    val lockVersion: Int = 1,
    val world: LockWorld,
    /** model-package qname → archive id (`sha256:…`). */
    val models: Map<String, String> = emptyMap(),
    /** executor/engine TYPE manifest name → archive id. */
    val manifests: Map<String, String> = emptyMap(),
    /** `"group:artifact"` → emit-plugin identity (BQ-4). */
    val plugins: Map<String, LockPlugin> = emptyMap(),
) {
    /** Every archive id the lock pins (world + models) — the fetch/frozen set. */
    fun archiveIds(): List<String> = listOf(world.archive) + models.values

    fun toToml(): String = TtrLockCodec.write(this)
}

data class LockWorld(
    val qname: String,
    val archive: String,
    /** K: the referenced platform-world content hash (present only for platform-composed worlds). */
    val platformWorld: LockPlatformWorld? = null,
)

data class LockPlatformWorld(
    val qname: String,
    val pin: String,
)

data class LockPlugin(
    val version: String,
    val sha256: String,
)

data class TtrLockResult(
    val lock: TtrLock?,
    val diagnostics: List<TtrpDiagnostic>,
)

object TtrLockCodec {
    private val knownTop = setOf("lockVersion", "world", "models", "manifests", "plugins")
    private val knownWorld = setOf("qname", "archive", "platformWorld")

    private fun lck001(
        path: String,
        detail: String,
    ) = TtrpDiagnostic(
        id = TtrpDiagnosticId.LCK_001,
        severity = Severity.ERROR,
        message = "ttr.lock: $detail (`$path`)",
        location = SourceLocation("ttr.lock", 1, 0, 1, 1, -1, -1),
        suggestedAlternative = TtrpDiagnosticId.LCK_001.suggestedAlternative,
    )

    /** Parse lock text. Unknown keys (any level) → LCK_001 naming the offending path; null lock on hard failure. */
    fun parse(content: String): TtrLockResult {
        val diags = mutableListOf<TtrpDiagnostic>()
        val parsed =
            try {
                Toml.parse(content)
            } catch (e: Exception) {
                return TtrLockResult(null, listOf(lck001("", "unparseable: ${e.message}")))
            }
        if (parsed.hasErrors()) {
            return TtrLockResult(null, listOf(lck001("", "unparseable: ${parsed.errors().first().message}")))
        }

        for (key in parsed.keySet()) {
            if (key !in knownTop) diags += lck001(key, "unknown top-level key")
        }

        val worldTable = parsed.getTable("world")
        if (worldTable == null) {
            diags += lck001("world", "the [world] table is required")
            return TtrLockResult(null, diags)
        }
        for (key in worldTable.keySet()) {
            if (key !in knownWorld) diags += lck001("world.$key", "unknown [world] key")
        }
        val platformWorld =
            worldTable.getTable("platformWorld")?.let { pw ->
                LockPlatformWorld(
                    qname = pw.getString("qname") ?: "",
                    pin = pw.getString("pin") ?: "",
                )
            }
        val world =
            LockWorld(
                qname = worldTable.getString("qname") ?: "",
                archive = worldTable.getString("archive") ?: "",
                platformWorld = platformWorld,
            )

        // tomlj re-parses a String key argument as a DOTTED PATH, so keys carrying `.`/`:`
        // (e.g. `shop.sales`, `org.tatrman:ttr-emit-bash`) MUST be accessed via the List<String>
        // overload — the literal-key form.
        fun stringMap(name: String): Map<String, String> =
            parsed.getTable(name)?.let { t ->
                t.keySet().associateWith { t.getString(listOf(it)) ?: "" }
            } ?: emptyMap()

        val plugins =
            parsed.getTable("plugins")?.let { t ->
                t.keySet().associateWith { k ->
                    val p = t.getTable(listOf(k))
                    LockPlugin(version = p?.getString("version") ?: "", sha256 = p?.getString("sha256") ?: "")
                }
            } ?: emptyMap()

        val lock =
            TtrLock(
                lockVersion = (parsed.getLong("lockVersion") ?: 1L).toInt(),
                world = world,
                models = stringMap("models"),
                manifests = stringMap("manifests"),
                plugins = plugins,
            )
        return TtrLockResult(lock, diags)
    }

    /** Deterministic writer — sorted sections/keys, fixed formatting; the bytes are hashed. */
    fun write(lock: TtrLock): String =
        buildString {
            appendLine("# ttr.lock — generated by `ttr fetch`; do not hand-edit. Canon pins only.")
            appendLine("lockVersion = ${lock.lockVersion}")
            appendLine()
            appendLine("[world]")
            appendLine("qname = ${q(lock.world.qname)}")
            appendLine("archive = ${q(lock.world.archive)}")
            lock.world.platformWorld?.let {
                appendLine("platformWorld = { qname = ${q(it.qname)}, pin = ${q(it.pin)} }")
            }
            if (lock.models.isNotEmpty()) {
                appendLine()
                appendLine("[models]")
                lock.models.toSortedMap().forEach { (k, v) -> appendLine("${q(k)} = ${q(v)}") }
            }
            if (lock.manifests.isNotEmpty()) {
                appendLine()
                appendLine("[manifests]")
                lock.manifests.toSortedMap().forEach { (k, v) -> appendLine("${q(k)} = ${q(v)}") }
            }
            if (lock.plugins.isNotEmpty()) {
                appendLine()
                appendLine("[plugins]")
                lock.plugins.toSortedMap().forEach { (k, v) ->
                    appendLine("${q(k)} = { version = ${q(v.version)}, sha256 = ${q(v.sha256)} }")
                }
            }
        }

    private fun q(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
